### ISSUE TITLE
load-dir value when  true-shapley is true

### ISSUE THREAD

**Issue by zhaoyueplc** [Fabien-Couthouis/XAI-in-RL#7] opened 2021-07-03 07:25 UTC
Hi ,

Would you help take a look at this issue?
I could run the run.py (\multiagent_particles\experiments\run.py)successfully.

But it failed when I would like to see some results about Shapley value. I have changed the code:
 parser.add_argument("--true-shapley", action="store_true",
                        default=**True**, help="Do not use Monte Carlo approximations") 

and getting the following error:
Traceback (most recent call last):
  File "C:/Users/hp/Downloads/XAI-in-RL-master/XAI-in-RL-master/multiagent_particles/experiments/run.py", line 227, in <module>
    U.load_state(arglist.load_dir)
  File "c:\users\hp\downloads\xai-in-rl-master\xai-in-rl-master\multiagent_particles\experiments\maddpg\common\tf_util.py", line 230, in load_state
    saver.restore(get_session(), fname)
  File "C:\ProgramData\Miniconda3\envs\XAI-in-RL-master\lib\site-packages\tensorflow\python\training\saver.py", line 1278, in restore
    compat.as_text(save_path))
ValueError: **The passed save_path is not a valid checkpoint: saves/model**

then followed the error I changed the argument:
    parser.add_argument("--load-dir", type=str, default="**experiments/saves/model**",
                        help="directory in which training state and model are loaded") //**in windows**
because experiments/saves/model is a path I think it should be find. The shapley_values can be import sucesfully in my windows with the following:
**from experiments.shapley_values** import monte_carlo_shapley_estimation, shapley_values
but not 
**from shapley_values** import monte_carlo_shapley_estimation, shapley_values

error:
WARNING:tensorflow:From c:\users\hp\downloads\xai-in-rl-master\xai-in-rl-master\multiagent_particles\experiments\maddpg\common\tf_util.py:229: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\XAI-in-RL-master\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.**checkpoint_management**) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.

Process finished with exit code -1073741819 (0xC0000005)

and about "code -1073741819 (0xC0000005)" I've tied to change the numpy , tensorflow, and h5py what other people said solved in their cases. It didn't help.

I suspect it's still a problem of the path to store the model, but it hasn't been improved after I changed the path several times. I notice the maddpg code (from openai) have a such setting "--load-dir", type=str, **default="",** , but it still doesn't work.
 By the way, what's the version of numpy , tensorflow, and h5py in your enviorment?

 I would be grateful/thankful if you could

Thank you.

**Comment by Fabien-Couthouis** [comment] 2021-07-03 07:44
Hello, 
The packages versions are available in this [environment.yml file](https://github.com/Fabien-Couthouis/XAI-in-RL/blob/master/multiagent_particles/environment.yml). Note that we used tensorflow 1.15 for this environment, which does not seem to be the version you are currently using, right? The --load-dir argument corresponds to the directory in which you saved the Tensorflow model so you have to change it depending of where you store your model. We have (examples of trained models)[https://github.com/Fabien-Couthouis/XAI-in-RL/tree/master/multiagent_particles/experiments/saves/run_10/episode_200000] if needed. In that case the --load dire argument would be "saves\\run_10\\episode_200000" on Windows, if you launch run.py from the experiment folder. The Shapley values can then be plotted using this script: https://github.com/Fabien-Couthouis/XAI-in-RL/blob/master/multiagent_particles/experiments/plots.py (not well documented, send me a message if you have difficulties with this part). 

Tell me if it helps.

**Comment by zhaoyueplc** [comment] 2021-07-04 21:43
Hi Fabien-Couthouis ，
Thanks for your quick response.
I still suspect that it is a path problem, which may not have much to do with the version of the dependent library. It works as long as I set true shaple to false.


Loading previous state...
2021-07-05 05:42:06.645793: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open saves\run_10\episode_200000: Unknown: NewRandomAccessFile failed to Create/Open: saves\run_10\episode_200000 : �ܾ����ʡ�
; Input/output error
2021-07-05 05:42:06.650368: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open saves\run_10\episode_200000: Unknown: NewRandomAccessFile failed to Create/Open: saves\run_10\episode_200000 : �ܾ����ʡ�
; Input/output error
2021-07-05 05:42:06.650868: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file saves\run_10\episode_200000: **Unknown: NewRandomAccessFile failed to Create/Open: saves\run_10\episode_200000** : �ܾ����ʡ�
; Input/output error

Process finished with exit code -1073741819 (0xC0000005)

**Comment by zhaoyueplc** [comment] 2021-07-05 07:06
I have the same version with environment.yml file, but still have the above error.

**Comment by Fabien-Couthouis** [comment] 2021-07-07 11:45
I have been able to reproduce this error: it happens when the path given to the `--load-dir` argument looks like `--load-dir=run_10\episode_200000`. In fact, we have to include the model prefix ("model" by default) in the path:  `--load-dir=run_10\episode_200000\model`. I must admit that the error was unclear.

I also pushed a fix which allows to load the 3vs1 models (I made some experiments with more agents but it was not concluding so I reverted the changes by default). After a `git pull`, you should be able to compute the Shapley values of a trained model, either with the `true-shapley` or `--shapley-M` argument. 

In case it is not clear:
- `true-shapley` can be used to compute the "true" Shapley values of agents by computing the mean reward over `--num-episodes` episodes (marginal contribution) for each possible coalition and for each agent. You have to change `--num-episodes` to something like 10-1000 (the higher number of episodes, the less variance you will have).
- `--shapley-M` can be used to compute the Shapley values using Monte-Carlo approximation, M corresponds to the number of episodes to sample with random coalitions (we used M=500 to 1000 in our experiments). You can set `--num-episodes=1` here.


The code is very experimental, do not hesitate to ask if something is not clear, otherwise you can close the issue.

**Closed** 2021-07-21 12:26 UTC
